<?php
/**
 * @category    Blockinformation
 * @package     Magenifieddebugging
 * @author   	Chris Manger (chris-manger.com)
 *
 * @var $this Mage_Core_Block_Template
 */
?>
<div id="magemagenified-debugging-forms-container">
    <div class="forms-wrapper invalid-checkout">
        Debugging feature does not work for the one page checkout.<br />
        Sorry for the inconvenience
    </div>
</div>